// <auto-generated />
using System;
using Helios.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Helios.Migrations.Migrations
{
    [DbContext(typeof(Database.HeliosDatabaseContext))]
    [Migration("20231218223003_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Helios.Core.Models.ElectricitySpotPrice+ElectricitySpotPrice", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EuroCentsPerKWh")
                        .HasColumnType("TEXT");

                    b.HasKey("Time");

                    b.ToTable("ElectricitySpotPrices");
                });

            modelBuilder.Entity("Helios.Core.Models.HouseholdEnergyReading+HouseholdEnergyReading", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<double>("Consumption")
                        .HasColumnType("REAL");

                    b.Property<double>("Production")
                        .HasColumnType("REAL");

                    b.HasKey("Time");

                    b.ToTable("HouseholdEnergyReadings");
                });

            modelBuilder.Entity("Helios.Core.Models.SolarPanelOutput+SolarPanelOutput", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<double>("Kwh")
                        .HasColumnType("REAL");

                    b.HasKey("Time");

                    b.ToTable("SolarPanelOutputs");
                });
#pragma warning restore 612, 618
        }
    }
}
