// <auto-generated />
using System;
using Helios.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Helios.Migrations.Migrations
{
    [DbContext(typeof(Database.HeliosDatabaseContext))]
    [Migration("20231216180834_ElectricitySpotPrices")]
    partial class ElectricitySpotPrices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Helios.Core.Models.ElectricitySpotPrice+ElectricitySpotPrice", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EuroCentsPerKWh")
                        .HasColumnType("TEXT");

                    b.HasKey("Time");

                    b.ToTable("ElectricitySpotPrices");
                });

            modelBuilder.Entity("Helios.Core.Models.EnergyMeasurement+EnergyMeasurement", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlowType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Kwh")
                        .HasColumnType("REAL");

                    b.HasKey("Time", "FlowType");

                    b.ToTable("EnergyMeasurements");
                });
#pragma warning restore 612, 618
        }
    }
}
