// <auto-generated />
using System;
using Helios.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Helios.Migrations.Migrations
{
    [DbContext(typeof(Database.HeliosDatabaseContext))]
    partial class HeliosDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Helios.Core.Models.EnergyMeasurement+EnergyMeasurement", b =>
                {
                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlowType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Kwh")
                        .HasColumnType("REAL");

                    b.HasKey("Time", "FlowType");

                    b.ToTable("EnergyMeasurements");
                });
#pragma warning restore 612, 618
        }
    }
}
